(() => {
"use strict";
const DB_NAME="StudyDeskMediaDB", DB_VERSION=1, STORE="media";
let db=null, items=[], activeFolder="all", search="", sort="newest", view="grid", viewerIndex=-1, viewerUrl=null;
const $=s=>document.querySelector(s);
const galleryPicker=$("#galleryPicker"), grid=$("#photoGrid"), folderNav=$("#folderNav"), toast=$("#toast");
const folderKey="studydeskGalleryFolders";
let folders=loadFolders();
function loadFolders(){try{const x=JSON.parse(localStorage.getItem(folderKey)||"[]");return Array.isArray(x)?x.filter(Boolean):[]}catch{return[]}}
function saveFolders(){localStorage.setItem(folderKey,JSON.stringify(folders))}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onsuccess=e=>{db=e.target.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function allRecords(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).index("type").getAll("image");r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function putRecord(x){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(x);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function deleteRecord(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function getRecord(id){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function esc(s){return String(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toastMsg(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove("show"),2200)}
const confirmModal=$("#appConfirmModal"),confirmTitle=$("#appConfirmTitle"),confirmMessage=$("#appConfirmMessage"),confirmOk=$("#appConfirmOk"),confirmCancel=$("#appConfirmCancel"),confirmClose=$("#appConfirmClose");
let confirmResolver=null;
function askConfirm(title,message){return new Promise(resolve=>{if(!confirmModal){resolve(window.confirm(title));return}confirmTitle.textContent=title;confirmMessage.textContent=message;confirmModal.classList.add("open");confirmModal.setAttribute("aria-hidden","false");confirmResolver=resolve})}
function closeConfirm(result=false){if(!confirmModal)return;confirmModal.classList.remove("open");confirmModal.setAttribute("aria-hidden","true");const r=confirmResolver;confirmResolver=null;if(r)r(result)}
confirmOk.onclick=()=>closeConfirm(true);confirmCancel.onclick=()=>closeConfirm(false);confirmClose.onclick=()=>closeConfirm(false);confirmModal.querySelector(".app-confirm-backdrop")?.addEventListener("click",()=>closeConfirm(false));

function folderOf(x){return x.folder||"بدون مجلد"}
function folderNames(){return ["كل الصور","المفضلة","بدون مجلد",...folders.filter(x=>!["كل الصور","المفضلة","بدون مجلد"].includes(x))]}
function currentItems(){let a=items.slice();if(activeFolder==="favorites")a=a.filter(x=>x.favorite);else if(activeFolder!=="all")a=a.filter(x=>folderOf(x)===activeFolder);if(search)a=a.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()));if(sort==="name")a.sort((a,b)=>a.name.localeCompare(b.name,"ar"));else if(sort==="oldest")a.sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));else a.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return a}
function renderFolders(){const counts={};items.forEach(x=>{const f=folderOf(x);counts[f]=(counts[f]||0)+1});folderNav.innerHTML="";folderNames().forEach(name=>{const b=document.createElement("button");b.type="button";b.className="folder-item";let active=false,icon="fa-folder";if(name==="كل الصور"){active=activeFolder==="all";icon="fa-images"}else if(name==="المفضلة"){active=activeFolder==="favorites";icon="fa-heart"}else{active=activeFolder===name;icon="fa-folder"}b.classList.toggle("active",active);b.innerHTML=`<i class="fa-solid ${icon}"></i><span>${esc(name)}</span><small class="folder-count">${name==="كل الصور"?items.length:name==="المفضلة"?items.filter(x=>x.favorite).length:(counts[name]||0)}</small>`;b.onclick=()=>{activeFolder=name==="كل الصور"?"all":name==="المفضلة"?"favorites":name;renderAll()};folderNav.appendChild(b)});$("#folderCount").textContent=folders.length+2}
function renderStats(){$("#totalCount").textContent=items.length;$("#favoriteCount").textContent=items.filter(x=>x.favorite).length}
function renderGrid(){const a=currentItems();grid.classList.toggle("list-view",view==="list");grid.innerHTML="";$("#emptyGallery").classList.toggle("show",!a.length);$("#activeFolderTitle h2").textContent=activeFolder==="all"?"كل الصور":activeFolder==="favorites"?"المفضلة":activeFolder; a.forEach((x,i)=>{const card=document.createElement("article");card.className="photo-card"+(x.favorite?" is-favorite":"");card.dataset.id=x.id;card.style.animationDelay=`${i*.035}s`;const u=URL.createObjectURL(x.blob);card.innerHTML=`<img src="${u}" alt="${esc(x.name)}" loading="lazy"><button class="corner-favorite" type="button" title="مفضلة"><i class="fa-${x.favorite?"solid":"regular"} fa-heart"></i></button><div class="photo-info"><span class="photo-name">${esc(x.name)}</span><div class="photo-actions"><button class="photo-action favorite ${x.favorite?"active":""}" type="button"><i class="fa-${x.favorite?"solid":"regular"} fa-heart"></i></button><button class="photo-action move" type="button"><i class="fa-solid fa-folder-open"></i></button><button class="photo-action delete" type="button"><i class="fa-solid fa-trash"></i></button></div></div>`;card.addEventListener("click",e=>{if(e.target.closest("button"))return;openViewer(a,i)});card.querySelector("img").ondblclick=e=>{e.preventDefault();openViewer(a,i)};card.querySelector(".corner-favorite").onclick=e=>{e.stopPropagation();toggleFavorite(x.id)};card.querySelector(".favorite").onclick=e=>{e.stopPropagation();toggleFavorite(x.id)};card.querySelector(".move").onclick=e=>{e.stopPropagation();openMove(x.id)};card.querySelector(".delete").onclick=e=>{e.stopPropagation();removeImage(x.id)};grid.appendChild(card)})}
function renderAll(){renderFolders();renderStats();renderGrid()}
async function toggleFavorite(id){const x=items.find(a=>a.id===id);if(!x)return;x.favorite=!x.favorite;await putRecord(x);renderAll();if(viewerIndex>=0)syncViewer()}
async function removeImage(id){const x=items.find(a=>a.id===id);if(!x)return;const ok=await askConfirm("هل تريد حذف الصورة؟",`سيتم حذف «${x.name}» من معرض StudyDesk ولا يمكن التراجع عن العملية.`);if(!ok)return;await deleteRecord(id);if(viewerIndex>=0){const vi=items.findIndex(x=>x.id===id);if(vi===viewerIndex)closeViewer()}items=await allRecords();renderAll();toastMsg("تم حذف الصورة")}
async function moveImage(id,folder){const x=items.find(a=>a.id===id);if(!x)return;x.folder=folder;await putRecord(x);items=await allRecords();renderAll();closeMove();toastMsg(`تم نقل الصورة إلى ${folder}`)}
function openMove(id){const box=$("#moveFolderList");box.innerHTML="";["بدون مجلد",...folders].forEach(f=>{const b=document.createElement("button");b.type="button";b.innerHTML=`<i class="fa-solid fa-folder"></i>${esc(f)}`;b.onclick=()=>moveImage(id,f);box.appendChild(b)});$("#moveModal").classList.add("open")}
function closeMove(){$("#moveModal").classList.remove("open")}
function openFolderModal(){$("#folderNameInput").value="";$("#folderModal").classList.add("open");setTimeout(()=>$("#folderNameInput").focus(),50)}
function closeFolderModal(){$("#folderModal").classList.remove("open")}
function saveFolder(){const n=$("#folderNameInput").value.trim();if(!n)return toastMsg("اكتب اسم المجلد");if(folderNames().includes(n))return toastMsg("اسم المجلد موجود بالفعل");folders.push(n);saveFolders();closeFolderModal();activeFolder=n;renderAll();toastMsg("تم إنشاء المجلد")}
function openViewer(list,index){viewerIndex=items.findIndex(x=>x.id===list[index].id);if(viewerIndex<0)return;$("#viewer").classList.add("open");$("#viewer").setAttribute("aria-hidden","false");syncViewer();document.body.style.overflow="hidden"}
function syncViewer(){if(viewerIndex<0||!items[viewerIndex])return;const x=items[viewerIndex];if(viewerUrl)URL.revokeObjectURL(viewerUrl);viewerUrl=URL.createObjectURL(x.blob);$("#viewerImage").src=viewerUrl;$("#viewerName").textContent=x.name;$("#viewerFolder").textContent=folderOf(x);$("#viewerCounter").textContent=`${viewerIndex+1} / ${items.length}`;$("#viewerFavorite").classList.toggle("active",!!x.favorite);$("#viewerFavorite i").className=`fa-${x.favorite?"solid":"regular"} fa-heart`}
function closeViewer(){$("#viewer").classList.remove("open");$("#viewer").setAttribute("aria-hidden","true");document.body.style.overflow="";if(viewerUrl){URL.revokeObjectURL(viewerUrl);viewerUrl=null}viewerIndex=-1}
function nextViewer(){if(!items.length)return;viewerIndex=(viewerIndex+1)%items.length;syncViewer()}
function prevViewer(){if(!items.length)return;viewerIndex=(viewerIndex-1+items.length)%items.length;syncViewer()}
async function importFiles(files){let count=0;for(const file of files){if(!file.type.startsWith("image/"))continue;await new Promise(r=>{const tx=db.transaction(STORE,"readwrite");const store=tx.objectStore(STORE);store.add({type:"image",name:file.name,mime:file.type,blob:file,createdAt:Date.now(),favorite:false,folder:activeFolder!=="all"&&activeFolder!=="favorites"?activeFolder:"بدون مجلد"});tx.oncomplete=r}) ;count++}items=await allRecords();renderAll();if(count)toastMsg(`تمت إضافة ${count} صورة`)}
galleryPicker.addEventListener("change",e=>{importFiles(Array.from(e.target.files||[]));e.target.value=""});$("#newFolder").onclick=openFolderModal;$("#folderSave").onclick=saveFolder;$("#folderCancel").onclick=closeFolderModal;$("#folderModalClose").onclick=closeFolderModal;$("#moveModalClose").onclick=closeMove;$("#searchGallery").oninput=e=>{search=e.target.value.trim();renderGrid()};$("#sortGallery").onchange=e=>{sort=e.target.value;renderGrid()};$("#viewGrid").onclick=()=>{view="grid";$("#viewGrid").classList.add("active");$("#viewList").classList.remove("active");renderGrid()};$("#viewList").onclick=()=>{view="list";$("#viewList").classList.add("active");$("#viewGrid").classList.remove("active");renderGrid()};$("#viewerClose").onclick=closeViewer;$("#viewerNext").onclick=nextViewer;$("#viewerPrev").onclick=prevViewer;$("#viewerFavorite").onclick=()=>viewerIndex>=0&&toggleFavorite(items[viewerIndex].id);$("#viewerMove").onclick=()=>viewerIndex>=0&&openMove(items[viewerIndex].id);$("#viewerDelete").onclick=()=>viewerIndex>=0&&removeImage(items[viewerIndex].id);$("#viewer").addEventListener("click",e=>{if(e.target.classList.contains("viewer-backdrop"))closeViewer()});$("#clearCurrentFolder").onclick=async()=>{const a=currentItems();if(!a.length)return toastMsg("مفيش صور هنا");const ok=await askConfirm("هل تريد تنظيف هذا القسم؟",`سيتم حذف ${a.length} صورة من العرض الحالي ولا يمكن التراجع عن العملية.`);if(!ok)return;for(const x of a)await deleteRecord(x.id);items=await allRecords();renderAll();toastMsg("تم التنظيف")};document.addEventListener("keydown",e=>{if(confirmModal?.classList.contains("open")){if(e.key==="Escape")closeConfirm(false);return}if($("#viewer").classList.contains("open")){if(e.key==="Escape")closeViewer();if(e.key==="ArrowLeft")nextViewer();if(e.key==="ArrowRight")prevViewer()}if(e.key==="Escape"){closeFolderModal();closeMove()}});
$("#themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("galleryTheme",document.body.classList.contains("dark")?"dark":"light");$("#themeToggle i").className=`fa-solid fa-${document.body.classList.contains("dark")?"sun":"moon"}`};if(localStorage.getItem("galleryTheme")==="dark"){$("#themeToggle").click()}
openDB().then(async()=>{items=await allRecords();renderAll()}).catch(()=>toastMsg("تعذر فتح تخزين المعرض"));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();